---
- name: Run showclock commands
  hosts: Linux
  gather_facts: false
  #connection: local

  tasks:

    - name: run show_vlan command via python script
      #raw: 'show clock'
      command: python /etc/ansible/REST/show-vlan.py
      register: vlan_result
    - name: Debug registered variables
      debug: var=vlan_result

